language: node_js
node_js: node
deploy:
  provider: heroku
  api_key:
    secure: ifTF8EpzqA48FbVUx0tDsTCYx5tns2LchJ4XMg2XQF3Ph8NClOKy5cWOZGpsGUi5UVkMznbW5MqKs86V6lMwOPSZsSezbYJxho0glgwI52RWr/rg4qjfPmF0uK+dr89kBR0I68XPxQksZibVZMFECjgzS6qO+hZmjAhGzQY0LuH8C3QPZAh442NtqXwRnJmimP/Eou9uzvc8RX/8CEg/zaWMgGGbNrRjuawgvyakJbRpmLY12BvbqAO6JY7yuWwLoWiIAymLMS9B9ZLZ7hHVUXdRDuvtS/GbWpzOnovOzpa7fhovMXsfTDBGr5wx/5LKLuKuTqV3gsRvRidb74pJZEQHKFt8sovTHfqcmArLdgZ0Jxo6ZOSkFFOIYU9fhBGoKAAWnucKqYU5Xq8lfJwRoLixNo9mjkmEonNzvUp5pgzbVx54QUDkva9y+9clNsuJvgGdzG/lo+0agVfX9eCpM8EmCZr4t+jPYXeh8ASG3B/xP1dC3vpmeE/I6sXj9bqOt3dRcX7ndp2jwJv/29Py0KBGq0XjH8zse0USMrye+kv4GYs2JjlisvX2AbOvfce1evFZeXRa1a6XYRJ4iHKsPjGFr8YecCeEU4SLk8OVM9pUjJPPsvnoHVB5NHBfosllfBPrAOzhn4CyhXo68V4evmwAM7I53LDB31XAFLgalmM=
  app: node-capstone-search-bestbuy
  on:
    repo: codysperoff/node-capstone-search-products-bestbuy
